version: "3"

# Services
services:
  # Twitter Producer
  twitter_stream:
    build: ./Twitter_Producer
    env_file:
      - ./credentials.env

  # Map Consumer
  map_consumer:
    build: ./Map_Consumer
    env_file:
      - ./credentials.env
    ports:
      - "9000:9000"

# Network
networks:
  default:
    external:
      name: kafka-network
