version: "3"

# Services
services:
  # producer
  twitter_stream:
    build: ./src/producer
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  # consumer
  twitter_consumer:
    build: ./src/consumer
    env_file:
      - ./.env
    ports:
      - "8080:8080"

  # Front-End
  front_end:
    build: ./src/front_end
    env_file:
      - ./.env
    ports:
      - "9000:9000"

# Network
networks:
  default:
    external:
      name: kafka-network
