version: "3"

# Services
services:
  # Twitter Producer
  twitter_stream:
    build: ./Twitter_Producer
    env_file:
      - ./credentials.env
    ports:
      - "8000:8000"

  # Map Consumer
  twitter_consumer:
    build: ./Twitter_Consumer
    env_file:
      - ./credentials.env
    ports:
      - "8080:8080"

  # Front-End
  front_end:
    build: ./Front_End
    env_file:
      - ./credentials.env
    ports:
      - "9000:9000"

# Network
networks:
  default:
    external:
      name: kafka-network

# -> When kafka instance in GCL says: "Set config.project" - gcloud config set project coronavirus-twitter-realtime
# -> How add firewall in google cloud
# gcloud compute firewall-rules create allow-node-api --description "node api channel" --allow tcp:2181
# gcloud compute firewall-rules create allow-node-api --description "node api channel" --allow tcp:9092

# -> Create Topic - https://sookocheff.com/post/kafka/deploying-kafka-to-gce/
# $KAFKA_HOME/bin/kafka-topics.sh
# $KAFKA_HOME/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test

# -> Para desplegar un cluster
# gcloud container clusters create twitter-realtime --num-nodes 2 --machine-type g1-small --region europe-north1

# -> Para tagear una imagen de docker
# docker tag twitterkafka_twitter_stream:latest eu.gcr.io/coronavirus-twitter-realtime/twitterkafka_twitter_stream:latest

# -> Para push imagen de docker a GoogleCloud
# docker push eu.gcr.io/coronavirus-twitter-realtime/twitterkafka_twitter_stream:latest