version: "3"

# Services
services:
  # Twitter Producer
  twitter_stream:
    build: ./Twitter_Producer
    env_file:
      - ./credentials.env
    ports:
      - "8000:8000"

  # Map Consumer
  twitter_consumer:
    build: ./Twitter_Consumer
    env_file:
      - ./credentials.env
    ports:
      - "8080:8080"

  # Front-End
  front_end:
    build: ./Front_End
    env_file:
      - ./credentials.env
    ports:
      - "9000:9000"

# Network
networks:
  default:
    external:
      name: kafka-network
